import SystemOfEquationsSolver as ses

a = ses.Frac(2, 3)   # 2/3
b = ses.Frac(14, 4)  # 7/2
c = ses.Frac(0, 5)   # 0
d = ses.Frac(-2, 4)  # -1/2
e = ses.Frac(2, -4)  # -1/2
f = ses.Frac(-4, -3) # 4/3

print(f"Frac strings:")
print(f"  a: {a}")
print(f"  b: {b}")
print(f"  c: {c}")
print(f"  d: {d}")
print(f"  e: {e}")
print(f"  f: {f}")
print()
print(f"Type convertion:")
print(f"  -float-")
print(f"  float(a): {float(a)}")
print(f"  float(b): {float(b)}")
print(f"  float(c): {float(c)}")
print()
print(f"  -int-")
print(f"  int(a): {int(a)}")
print(f"  int(b): {int(b)}")
print(f"  int(c): {int(c)}")
print()
print(f"  -bool-")
print(f"  bool(a): {bool(a)}")
print(f"  bool(b): {bool(b)}")
print(f"  bool(c): {bool(c)}")
print()
print(f"Comparison")
print(f"  -equal-")
print(f"  a == a: {a == a}")
print(f"  a == b: {a == b}")
print()
print(f"  -not equal-")
print(f"  a != a: {a != a}")
print(f"  a != b: {a != b}")
print()
print(f"  -less than-")
print(f"  a < a: {a < a}")
print(f"  a < b: {a < b}")
print(f"  a < c: {a < c}")
print(f"  c < a: {c < a}")
print()
print(f"  -less than or equal-")
print(f"  a <= a: {a <= a}")
print(f"  a <= b: {a <= b}")
print(f"  a <= c: {a <= c}")
print(f"  c <= a: {c <= a}")
print()
print(f"  -greater than-")
print(f"  a > a: {a > a}")
print(f"  a > b: {a > b}")
print(f"  a > c: {a > c}")
print(f"  c > a: {c > a}")
print()
print(f"  -greater than or equal-")
print(f"  a >= a: {a >= a}")
print(f"  a >= b: {a >= b}")
print(f"  a >= c: {a >= c}")
print(f"  c >= a: {c >= a}")
print()
print(f"Operations")
print(f"  -addition-")
print(f"  a + a: {a + a}")
print(f"  a + b: {a + b}")
print(f"  b + a: {b + a}")
print(f"  a + c: {a + c}")
print()